name: diff_cache
description: "A new Flutter project."
version: 0.0.1
homepage: git@github.com:yutaotao2822/diffCache.git

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  uuid: ^4.2.1
  shared_preferences: ^2.0.8 # 持久化管理
  dio: ^5.2.0+1 # 网络请求框架
  path_provider: ^2.1.1  # 使用最新版本

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.diff_cache
        pluginClass: DiffCachePlugin
      ios:
        pluginClass: DiffCachePlugin
